### ISSUE TITLE
Atom crash on startup

### ISSUE THREAD

**Issue by NicoHood** [tensor5/arch-atom#36] opened 2016-08-13 06:24 UTC
Hey,
I switched from the normal atom AUR package to the official one. But when I start Atom I get:
![screenshot_2016-08-13_08-22-35](https://cloud.githubusercontent.com/assets/6888294/17641813/2459f28a-612f-11e6-9f44-5b2d68465bf2.png)

All I did was to uninstall the old package via -Rs and install the new package. Running on kernel 4.4.16-1 with atom-1.9.8-2. I did not do a reboot yet, as I cannot do this in the next days for several reasons.

Dmesg give me things like this:
```
[196952.142119] atom[29471]: segfault at 128e ip 00007f151ff85773 sp 00007ffd7a0d2ef0 error 4 in libnode.so[7f151f704000+1110000]
[198233.086881] traps: electron[13523] trap invalid opcode ip:18a4291 sp:7fffae2bf1c0 error:0 in electron[400000+3b8b000]

[317352.294754] traps: electron[13336] trap invalid opcode ip:18a4291 sp:7ffd9e3c23d0 error:0 in electron[400000+3b8b000]
[317415.025748] traps: electron[13403] trap invalid opcode ip:18a4291 sp:7ffe94ae5960 error:0 in electron[400000+3b8b000]
```

**Comment by tensor5** [comment] 2016-08-13 06:37
Duplicate of #34.

**Closed by tensor5** 2016-08-13 06:37 UTC
Labels: duplicate

**Comment by NicoHood** [comment] 2016-08-13 06:43
Okay, i wasent sure if its the same bug.

**Comment by tensor5** [comment] 2016-08-13 06:46
No problem.
